export const SAMPLE_PRODUCTS = [
    {
        id: 1,
        name: "iPhone 15",
        brand: "Apple",
        category: "Phone",
        price: 999,
        image: "📱",
    },
    {
        id: 2,
        name: "Galaxy S24",
        brand: "Samsung",
        category: "Phone",
        price: 899,
        image: "📱",
    },
    {
        id: 3,
        name: "MacBook Air",
        brand: "Apple",
        category: "Laptop",
        price: 1299,
        image: "💻",
    },
    {
        id: 4,
        name: "Dell XPS",
        brand: "Dell",
        category: "Laptop",
        price: 999,
        image: "💻",
    },
    {
        id: 5,
        name: "Nike Shoes",
        brand: "Nike",
        category: "Shoes",
        price: 120,
        image: "👟",
    },
    {
        id: 6,
        name: "Adidas Shoes",
        brand: "Adidas",
        category: "Shoes",
        price: 100,
        image: "👟",
    },
    {
        id: 7,
        name: "iPad Pro",
        brand: "Apple",
        category: "Tablet",
        price: 799,
        image: "📱",
    },
    {
        id: 8,
        name: "Galaxy Tab",
        brand: "Samsung",
        category: "Tablet",
        price: 599,
        image: "📱",
    },
];